### ISSUE TITLE
WebGL for OpenGL, WebVulkan for Vulkan

### ISSUE THREAD

**Issue by RUSshy** [KhronosGroup/WebGLNext-Proposals#5]
Please stay generic, and don't try to make Mozilla the detentor of the Vulkan for web brand

Thanks

**Comment by Kangz** [comment]
Mozilla uses the name Obsidian, not WebVulkan. Also AFAIK Vulkan is a trademark of the Khronos Group.

Thanks for your very constructive input, closing.
